### List referencing 

In [6]:
a = [1,2,3]
b = a
b

[1, 2, 3]

In [7]:
b[0] = "a"
a

['a', 2, 3]

In [8]:
b

['a', 2, 3]

### List copy

In [13]:
a = [1,2,3]
b = a[:]

In [14]:
b[0] = ['bbi']
a

[1, 2, 3]

In [15]:
b

[['bbi'], 2, 3]

In [1]:
import pandas as pd

In [14]:
data = {
    "A A":[1,2,3],
    "B B":[4,5,6]
}
df = pd.DataFrame(data)

In [15]:
df

A A  B B
0    1    4
1    2    5
2    3    6

In [18]:
df.loc[0,'B B']

4

In [20]:
df.loc[0:1,"B B"]

0    4
1    5
Name: B B, dtype: int64

In [21]:
import numpy as np

In [25]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [26]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out


array([0, 1])

In [28]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [29]:
with open("Example3.txt","w") as file1:
  
file1.write("This is line C\n")

IndentationError: expected an indented block (2935992726.py, line 3)

In [32]:
x=df.[['Length']]
x

SyntaxError: invalid syntax (1730585191.py, line 1)

In [33]:
name = "Lizz"
name[0:2]

'Li'

In [34]:
var = "01234567"
var[::2]

'0246'

In [44]:
a = ["word","bad"]
"this training is bad".split()

['this', 'training', 'is', 'bad']

In [46]:
sorted(a)

['bad', 'word']

In [47]:
a = np.array([0,1,0,1,0])
b = np.array([1,0,1,0,1])
a/b

C:\Users\ZhengXiqian\AppData\Local\Temp\ipykernel_7212\229672931.py:3: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 0., inf,  0., inf,  0.])